feat: added docs for building sg hdb flats
ASEAN-Build-The-Earth/ASEAN-Docs pull request #34
Opened 2023-07-15 06:19 UTC by Codestian

Added a simple guide for building HDB flats in Singapore. Will be adding more details with images soon.

2023-07-15 06:31 UTC, StoneMcYT requested changes

2023-07-15 06:31 UTC, StoneMcYT commented on docs.builder-guide/building/building-hdbs/setup.md
![image](https://github.com/ASEAN-Build-The-Earth/ASEAN-Docs/assets/67421882/8b27972d-ef2c-4dae-8b6a-d538a9fb2861)

This is the only ones we will have issues with, since we're pushing for a near full vanilla setup as the recomandation

For this I would suggest
Creating a 'Building in Singapore' page with a short description, mentions of singapore archture, current buildsites/completed areas in singapore
Then have a 'Extra recommendations' bit instead of it being labeled as the main setup
![image](https://github.com/ASEAN-Build-The-Earth/ASEAN-Docs/assets/67421882/6484d7ee-2fe9-4e5e-a20c-23e5f6421b7f)

2023-07-15 06:31 UTC, StoneMcYT commented on docs.builder-guide/building/building-hdbs/terminology.md
Seems alright but i recommend adding some images in

2023-07-15 06:31 UTC, StoneMcYT commented on docs.builder-guide/building/building-hdbs/type-of-units.md
![image](https://github.com/ASEAN-Build-The-Earth/ASEAN-Docs/assets/67421882/0ea28be2-a6f6-4881-b5c0-792ece378500)

See if you can add in a bit more images/floor plan references just to add a bit more visual niceness to it since this guide will be for all incoming/new/to be builders

2023-07-15 06:32 UTC, StoneMcYT commented on docs.builder-guide/building/building-hdbs/setup.md
Dont want it to sound like a modded setup is the to go/must use/only option 
Since we've got full vanilla support incoming

2023-07-15 10:40 UTC, tintinkung commented
Some of the content may be duplicate to the parent BTE Building page tho
> like the angle tips already exist in BTE Building page
> ![image](https://github.com/ASEAN-Build-The-Earth/ASEAN-Docs/assets/77855014/b426c938-cab4-4d43-8930-d315d6ecde5f)
> ![image](https://github.com/ASEAN-Build-The-Earth/ASEAN-Docs/assets/77855014/33173eb0-9665-4c5e-9a47-9651ee0d959a)

Also you could move the `Setup` page ups being mods recommendation page, since our server are now merged (Master 3.0)

2024-08-16 15:13 UTC, tintinkung commented
## Dead Chat :lock:

2024-08-16 15:13 UTC, closed without merging